<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="1" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value=".4826" />
  <xacro:property name="base_length" value=".4826" />
  <xacro:property name="base_height" value=".78105" />
  <xacro:property name="wheel_mass" value="0.2" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.040" />
  <xacro:property name="wheel_space" value="0.005" />
  <xacro:property name="wheel_radius" value="0.0508" />
  <xacro:property name="caster_wheel_mass" value="0.1" /> <!-- arbitrary value for caster wheel mass -->
  <xacro:property name="caster_wheel_radius" value="0.0508" />
  <xacro:property name="caster_x" value="0.358" />
  <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->

  <!-- Base Link =============================================================================================-->

  <link name="${prefix}base_link">
  </link>


  <!-- Chassis link ====================================================================================-->

  <joint name="${prefix}chassis_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}chassis"/>
    <origin xyz="-.0623 0 0"/>
  </joint>

  <link name="${prefix}chassis">
    <visual>
      <origin xyz="${base_width/2} 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="${base_width/2} 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_length} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="${base_width/2} 0 ${base_height/2}" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
        iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
        izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <!-- LEFT wheel Joint/link ===========================================================================-->

    <joint name="${prefix}left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_wheel"/>
      <origin xyz="0 -${(base_width/2) + (wheel_len/2) + wheel_space} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <link name="${prefix}left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

    <!-- right wheel Joint/Link =========================================================================-->

    <joint name="${prefix}right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_wheel"/>
      <origin xyz="0 ${(base_width/2) + (wheel_len/2) + wheel_space} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <link name="${prefix}right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
      </link>

    <!-- Caster wheel Joint/Link =======================================================================-->

    <joint name="${prefix}caster_wheel_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}caster_wheel"/>
      <origin xyz="${caster_x} 0 0" rpy="0 0 0"/>
    </joint>

   
    <link name="${prefix}caster_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_wheel_radius}"/>
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${caster_wheel_mass}"/>
        <inertia
          ixx="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" ixy="0.0" ixz="0.0"
          iyy="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}" iyz="0.0"
          izz="${caster_wheel_mass * 0.4 * (caster_wheel_radius * caster_wheel_radius)}"/>
        </inertial>
      </link>

    <!-- lidar top cover link/joint ====================================================================================-->

    <joint name="${prefix}lidar_cover_top_joint" type="fixed">
      <parent link="${prefix}chassis"/>
      <child link="${prefix}cover_top"/>
      <origin xyz="${.4826 + .05 + .001} 0 ${.15-.02-.01+.005}"/>
    </joint>
    
    <link name="${prefix}cover_top">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".06" length=".01"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".06" length=".01"/>
      </geometry>
    </collision>
    </link>


    <joint name="${prefix}lidar_cover_top_box_joint" type="fixed">
      <parent link="${prefix}cover_top"/>
      <child link="${prefix}cover_top_box"/>
      <origin xyz="-.03 0 0"/>
    </joint>
    
    <link name="${prefix}cover_top_box">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".06 .12 .01"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".06 .06 .01"/>
      </geometry>
    </collision>
    </link>

    <!-- lidar bottom cover link/joint ====================================================================================-->

    <joint name="${prefix}lidar_cover_bottom_joint" type="fixed">
      <parent link="${prefix}chassis"/>
      <child link="${prefix}cover_bottom"/>
      <origin xyz="${.4826 + .05 + .001} 0 ${.15+.02+.01-.005}"/>
    </joint>
    
    <link name="${prefix}cover_bottom">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".06" length=".01"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius=".06" length=".01"/>
      </geometry>
    </collision>
    </link>

    <joint name="${prefix}lidar_cover_bottom_box_joint" type="fixed">
      <parent link="${prefix}cover_bottom"/>
      <child link="${prefix}cover_bottom_box"/>
      <origin xyz="-.03 0 0"/>
    </joint>
    
    <link name="${prefix}cover_bottom_box">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".06 .12 .01"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size=".06 .06 .01"/>
      </geometry>
    </collision>
    </link>

  </xacro:macro>

</robot>